spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&servetTimezone=UTC&useLegacyDate
    username: postgres
    password: 1108
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate.format_sql: true

    logging:
      level:
        org:
          hibernate:
            type: trace

